<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

// Public Routes
Route::get('/', function () {
    if (auth()->check()) {
        return redirect()->route('dashboard'); // Redirect to dashboard if logged in
    }
    return view('welcome'); // Show welcome page if not logged in
});
// Authenticated Routes
Route::middleware(['auth', 'verified'])->group(function () {
    // Dashboard
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    // CRM Resources
    Route::resource('contacts', ContactController::class)->middleware('auth');
    Route::resource('leads', LeadController::class)->middleware('auth');
    Route::resource('tasks', TaskController::class)->middleware('auth');

    // Profile Routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('/reload-captcha', function () {
    return response()->json(['captcha' => captcha_img()]);
});

// Authentication Routes (Generated by Laravel Breeze)
require __DIR__.'/auth.php';
